version: '1'

services:
  postgres:
    image: postgres 
    container_name: postgresql
    ports:
      - "5432:5432"
    volumes:
      - /media/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=tester
      - POSTGRES_PASSWORD=testing
      - POSTGRES_DB=test
    restart: always

